Repository JowellDev/jeriel, pull requests merged in 2025-07, with the labels that each got.

#199 Fix/managers selection
  app/routes/_dashboard/departments.($id)/components/main-form.tsx
  app/routes/_dashboard/tribes.($id)/components/tribe-form-dialog.tsx
  compose.yml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug

#202 update pnpm version
  Dockerfile
  package.json
Labels: bug

#203 update depencies
  package.json
Labels: bug, dependencies

#198 Feature/mise jour de l ajout de fid le une famille d honneur
  app/routes/_dashboard/honor-families.$id_.details/action.server.ts
  app/routes/_dashboard/honor-families.$id_.details/components/assistant-form.tsx
  app/routes/_dashboard/honor-families.$id_.details/components/member-form.tsx
  app/routes/_dashboard/honor-families.$id_.details/components/upload-form.tsx
  app/routes/_dashboard/honor-families.$id_.details/schema.ts
  app/routes/_dashboard/honor-families.$id_.details/types.ts
  app/routes/_dashboard/honor-families.$id_.details/utils/utils.server.ts
  app/routes/_dashboard/honor-families.($id)/components/form-dialog.tsx
  app/shared/constants.ts
  app/utils/member.ts
  prisma/migrations/20250711104614_make_integration_date_of_user_deletion_on_cascase/migration.sql
  prisma/schema.prisma
Labels: feature

#207 Feat/allow tribe manager selection
  app/routes/_dashboard/tribe/action.server.ts
  app/routes/_dashboard/tribes.($id)/components/tribe-form-dialog.tsx
  app/routes/_dashboard/tribes_.$id.details/_index.tsx
  app/routes/_dashboard/tribes_.$id.details/action.server.ts
  app/routes/_dashboard/tribes_.$id.details/constants.ts
  app/routes/_dashboard/tribes_.$id.details/types.ts
  app/routes/_dashboard/tribes_.$id.details/utils/utils.server.ts
  app/routes/api/get-members/_index.ts
  app/shared/forms/member-form.tsx
  app/shared/schema.ts
Labels: feature
